FROM python:3.12

WORKDIR /bot_app

COPY requirements.txt /bot_app

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . /bot_app

# RUN alembic upgrade head

# CMD ["python", "-m", "src.bot.app.main"]