"""empty message

Revision ID: 977d355a854a
Revises: fdc7e10b77f2
Create Date: 2024-10-20 12:15:00.052969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977d355a854a'
down_revision: Union[str, None] = 'fdc7e10b77f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('order', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('feedback', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
