"""empty message

Revision ID: ecb7fc98be89
Revises: 3a131b61411a
Create Date: 2024-10-04 16:52:30.609763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb7fc98be89'
down_revision: Union[str, None] = '3a131b61411a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('order_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'feedback', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'order_id')
    # ### end Alembic commands ###
