"""empty message

Revision ID: 77371c329a67
Revises: 37b29d0aa4ca
Create Date: 2024-10-20 12:04:27.323525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77371c329a67'
down_revision: Union[str, None] = '37b29d0aa4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedback_product_id_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'product', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_product_id_fkey', 'feedback', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
