"""empty message

Revision ID: fdc7e10b77f2
Revises: 77371c329a67
Create Date: 2024-10-20 12:10:02.205097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc7e10b77f2'
down_revision: Union[str, None] = '77371c329a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_product_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'product', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_product_id_fkey', 'order', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
