"""empty message

Revision ID: 3a131b61411a
Revises: b2e44fad5453
Create Date: 2024-10-01 17:34:30.554832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a131b61411a'
down_revision: Union[str, None] = 'b2e44fad5453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback', 'stars',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product_name_game_category_index', 'product', [sa.text("immutable_unaccent(lower((((COALESCE(name, ''::character varying)::text || COALESCE(game_name, ''::character varying)::text) || COALESCE(category, ''::character varying)::text) || COALESCE(description, ''::character varying)::text) || COALESCE(instruction, ''::character varying)::text))")], unique=False, postgresql_using='gin')
    op.alter_column('feedback', 'stars',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
